### ISSUE TITLE
Error 8: TypeError: 'set' object does not support indexing

### ISSUE THREAD

**Issue by hannoL** [lynnlyc/droidbot#1]
I got following error, if I try **-env static** and **-event static**.

Can you reproduce this? Or did you need any further information?

## Environment:
* Ubuntu 14.04.LTS 64bit
* GIT: 36978bc
* Sample: http://www.h-lemoine.de/ctf.hack.lu_2011/0xA1EA512A.apk - NoMalware

## Error Message run 1

	hanno@dockerDroidBox:~/work/PycharmProjects/gsoc_droidbot$ python start.py -d emulator-5554 -a ~/mobileSamples/myApkTresor/0xA1EA512A.apk -env static -event static -o ~/mobileSamples/out/
	Connecting to a device with serialno=emulator-5554 with a timeout of 60 secs...
	Connected to device with serialno=emulator-5554
	Actual device serialno=emulator-5554
	INFO:TelnetConsole:telnet successfully initiated, the addr is (localhost:5554)
	INFO:AppEnvManager:start deploying environment, policy is static
	INFO:AppEnvManager:finish deploying environment, policy is static
	INFO:AppEventManager:start sending events, policy is static
	Traceback (most recent call last):
	  File "start.py", line 59, in <module>
	    main()
	  File "start.py", line 54, in main
	    droidbot.start()
	  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/droidbot.py", line 57, in start
	    event_manager.start()
	  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/app_event.py", line 596, in start
	    self.event_factory.start(self)
	  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/app_event.py", line 622, in start
	    event = self.generate_event()
	  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/app_event.py", line 687, in generate_event
	    event = IntentEvent(random.choice(self.possible_broadcasts))
	  File "/usr/lib/python2.7/random.py", line 273, in choice
	    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
	TypeError: 'set' object does not support indexing

## Error Message Run 2
Directly start again, with same options

	hanno@dockerDroidBox:~/work/PycharmProjects/gsoc_droidbot$ python start.py -d emulator-5554 -a ~/mobileSamples/myApkTresor/0xA1EA512A.apk -env static -event static -o ~/mobileSamples/out/
	Connecting to a device with serialno=emulator-5554 with a timeout of 60 secs...
	Connected to device with serialno=emulator-5554
	Actual device serialno=emulator-5554
	INFO:TelnetConsole:telnet successfully initiated, the addr is (localhost:5554)
	INFO:AppEnvManager:start deploying environment, policy is static
	INFO:AppEnvManager:finish deploying environment, policy is static
	INFO:AppEventManager:start sending events, policy is static
	INFO:Device:sending event: {'y': 32.8591446899452, 'x': 437.5584810568152, 'event_type': 'touch'}
	INFO:Device:sending event: {'end_y': 498.1677162695015, 'end_x': 315.68866845993193, 'event_type': 'drag', 'start_x': 210.69466125667248, 'start_y': 328.3185878673619, 'duration': 1000}
	INFO:Device:sending event: {'y': 493.094584939305, 'x': 154.26444767996884, 'duration': 2000, 'event_type': 'long_touch'}
	INFO:Device:sending event: {'y': 444.3006494011745, 'x': 113.67011265128552, 'event_type': 'touch'}
	INFO:Device:sending event: {'end_y': 672.0457399110186, 'end_x': 478.18141328307485, 'event_type': 'drag', 'start_x': 466.8914364961149, 'start_y': 92.84503510691451, 'duration': 1000}
	INFO:Device:sending event: {'y': 68.3811014163477, 'x': 17.85127948145888, 'event_type': 'touch'}
	INFO:Device:sending event: {'y': 658.3341716339296, 'x': 100.44058556767399, 'duration': 2000, 'event_type': 'long_touch'}
	INFO:Device:sending event: {'end_y': 115.7405872155012, 'end_x': 475.0347537349947, 'event_type': 'drag', 'start_x': 366.2377565833698, 'start_y': 623.9578109991636, 'duration': 1000}
	Traceback (most recent call last):
	  File "start.py", line 59, in <module>
	    main()
	  File "start.py", line 54, in main
	    droidbot.start()
	  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/droidbot.py", line 57, in start
	    event_manager.start()
	  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/app_event.py", line 596, in start
	    self.event_factory.start(self)
	  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/app_event.py", line 622, in start
	    event = self.generate_event()
	  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/app_event.py", line 687, in generate_event
	    event = IntentEvent(random.choice(self.possible_broadcasts))
	  File "/usr/lib/python2.7/random.py", line 273, in choice
	    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
	TypeError: 'set' object does not support indexing

**Comment by lynnlyc** [comment]
random.choice() doesn't accept set-type parameter.
Convert it to list type should solve this issue.

**Comment by hannoL** [comment]
Now with 866657a I have a new error Message: **IndexError: list index out of range**

```
hanno@dockerDroidBox:~/work/PycharmProjects/gsoc_droidbot$ python start.py -d emulator-5554 -a ~/mobileSamples/myApkTresor/0xA1EA512A.apk -env static -event static -o ~/mobileSamples/out/
Connecting to a device with serialno=emulator-5554 with a timeout of 60 secs...
Connected to device with serialno=emulator-5554
Actual device serialno=emulator-5554
INFO:TelnetConsole:telnet successfully initiated, the addr is (localhost:5554)
INFO:AppEnvManager:start deploying environment, policy is static
INFO:AppEnvManager:finish deploying environment, policy is static
INFO:AppEventManager:start sending events, policy is static
INFO:Device:sending event: {'y': 578.6571309256251, 'x': 7.700258676474885, 'event_type': 'touch'}
INFO:Device:sending event: {'y': 302.5150305392291, 'x': 269.4077683002539, 'event_type': 'touch'}
Traceback (most recent call last):
  File "start.py", line 59, in <module>
    main()
  File "start.py", line 54, in main
    droidbot.start()
  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/droidbot.py", line 61, in start
    event_manager.start()
  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/app_event.py", line 599, in start
    self.event_factory.start(self)
  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/app_event.py", line 625, in start
    event = self.generate_event()
  File "/home/hanno/work/PycharmProjects/gsoc_droidbot/droidbot/app_event.py", line 690, in generate_event
    event = IntentEvent(random.choice(list(self.possible_broadcasts)))
  File "/usr/lib/python2.7/random.py", line 273, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
```

**Comment by lynnlyc** [comment]
Added non-empty check before each random.choice().

**Comment by hannoL** [comment]
Thank You. That works fine with #d19fb0f.
