### ISSUE TITLE
Docker build error (licences)

### ISSUE THREAD

**Issue by Nooby4Ever** [lynnlyc/droidbot#16]
When trying to build droidbot with docker using:
```
git clone https://github.com/lynnlyc/droidbot.git
docker build -t honeynet/droidbot droidbot
```

Gives the folowing licence issues:

> ...
> November 20, 2015
> Do you accept the license 'android-sdk-license-c81a61d9' [y/n]: n
> ...
> June 2014.
> Do you accept the license 'android-sdk-preview-license-d099d938' [y/n]: n
> ...
> Do you accept the license 'mips-android-sysimage-license-acdab23e' [y/n]: n
> ...
> Error: Target id is not valid. Use 'android list targets' to get the target ids.
> The command '/bin/sh -c expect /build/accept-licenses "android update sdk --no-ui --all --filter platform-tool,system-image,android-16" "android-sdk-license-5be876d5" &&     echo "\n"| android create avd -n droidbox -t 1 -d 2' returned a non-zero code: 1

If i alter /droidbot/docker/accept-licences to accept all licences i get the folowing error (set line 20 to y):

> ...
> Installing Archives:
>   Preparing to install archives
>   Downloading Android SDK Platform-tools, revision 23.1
>   Installing Android SDK Platform-tools, revision 23.1
>   Stopping ADB server failed (code -1).
>     Installed Android SDK Platform-tools, revision 23.199%)
>   Downloading Android SDK Platform-tools, revision 24 rc2
>   Installing Android SDK Platform-tools, revision 24 rc2
>     Stopping ADB server succeeded.
>     Installed Android SDK Platform-tools, revision 24 rc299%)
>   Downloading SDK Platform Android 4.1.2, API 16, revision 5
>   Installing SDK Platform Android 4.1.2, API 16, revision 5
>     Installed SDK Platform Android 4.1.2, API 16, revision 596%)
>   Skipping 'Android TV ARM EABI v7a System Image, Android API 23, revision 3'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'Android TV Intel x86 Atom System Image, Android API 23, revision 3'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'Android Wear ARM EABI v7a System Image, Android API 23, revision 3'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'Android Wear Intel x86 Atom System Image, Android API 23, revision 3'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'ARM EABI v7a System Image, Android API 23, revision 3'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'Intel x86 Atom_64 System Image, Android API 23, revision 8'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'Intel x86 Atom System Image, Android API 23, revision 8'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'Google APIs ARM EABI v7a System Image, Android API 23, revision 7'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'Google APIs Intel x86 Atom_64 System Image, Android API 23, revision 12'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'Google APIs Intel x86 Atom System Image, Android API 23, revision 12'; it depends on 'SDK Platform Android 6.0, API 23, revision 3' which was not installed.
>   Skipping 'Android TV Intel x86 Atom System Image, Android API N, revision 2'; it depends on 'SDK Platform Android N Preview, revision 2' which was not installed.
>   Skipping 'Intel x86 Atom_64 System Image, Android API N, revision 2'; it depends on 'SDK Platform Android N Preview, revision 2' which was not installed.
>   Skipping 'Intel x86 Atom System Image, Android API N, revision 2'; it depends on 'SDK Platform Android N Preview, revision 2' which was not installed.
>   Skipping 'Android TV ARM EABI v7a System Image, Android API 22, revision 1'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'Android TV Intel x86 Atom System Image, Android API 22, revision 1'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'Android Wear ARM EABI v7a System Image, Android API 22, revision 7'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'Android Wear Intel x86 Atom System Image, Android API 22, revision 7'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'ARM EABI v7a System Image, Android API 22, revision 1'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'Intel x86 Atom_64 System Image, Android API 22, revision 4'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'Intel x86 Atom System Image, Android API 22, revision 4'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'Google APIs ARM EABI v7a System Image, Android API 22, revision 1'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'Google APIs Intel x86 Atom_64 System Image, Android API 22, revision 4'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'Google APIs Intel x86 Atom System Image, Android API 22, revision 4'; it depends on 'SDK Platform Android 5.1.1, API 22, revision 2' which was not installed.
>   Skipping 'Android TV ARM EABI v7a System Image, Android API 21, revision 3'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'Android TV Intel x86 Atom System Image, Android API 21, revision 3'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'Android Wear ARM EABI v7a System Image, Android API 21, revision 3'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'Android Wear Intel x86 Atom System Image, Android API 21, revision 3'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'ARM EABI v7a System Image, Android API 21, revision 3'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'Intel x86 Atom_64 System Image, Android API 21, revision 3'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'Intel x86 Atom System Image, Android API 21, revision 3'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'Google APIs ARM EABI v7a System Image, Android API 21, revision 10'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'Google APIs Intel x86 Atom_64 System Image, Android API 21, revision 10'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'Google APIs Intel x86 Atom System Image, Android API 21, revision 10'; it depends on 'SDK Platform Android 5.0.1, API 21, revision 2' which was not installed.
>   Skipping 'Android Wear ARM EABI v7a System Image, Android API 20, revision 4'; it depends on 'SDK Platform Android 4.4W.2, API 20, revision 2' which was not installed.
>   Skipping 'Android Wear Intel x86 Atom System Image, Android API 20, revision 4'; it depends on 'SDK Platform Android 4.4W.2, API 20, revision 2' which was not installed.
>   Skipping 'ARM EABI v7a System Image, Android API 19, revision 3'; it depends on 'SDK Platform Android 4.4.2, API 19, revision 4' which was not installed.
>   Skipping 'Intel x86 Atom System Image, Android API 19, revision 3'; it depends on 'SDK Platform Android 4.4.2, API 19, revision 4' which was not installed.
>   Skipping 'ARM EABI v7a System Image, Android API 18, revision 3'; it depends on 'SDK Platform Android 4.3.1, API 18, revision 3' which was not installed.
>   Skipping 'Intel x86 Atom System Image, Android API 18, revision 2'; it depends on 'SDK Platform Android 4.3.1, API 18, revision 3' which was not installed.
>   Skipping 'ARM EABI v7a System Image, Android API 17, revision 3'; it depends on 'SDK Platform Android 4.2.2, API 17, revision 3' which was not installed.
>   Skipping 'Intel x86 Atom System Image, Android API 17, revision 2'; it depends on 'SDK Platform Android 4.2.2, API 17, revision 3' which was not installed.
>   Skipping 'MIPS System Image, Android API 17, revision 1'; it depends on 'SDK Platform Android 4.2.2, API 17, revision 3' which was not installed.
>   Downloading ARM EABI v7a System Image, Android API 16, revision 4
>   Installing ARM EABI v7a System Image, Android API 16, revision 4
>     Installed ARM EABI v7a System Image, Android API 16, revision 499%)
>   Downloading Intel x86 Atom System Image, Android API 16, revision 2
>   Installing Intel x86 Atom System Image, Android API 16, revision 2
>     Installed Intel x86 Atom System Image, Android API 16, revision 299%)
>   Downloading MIPS System Image, Android API 16, revision 1
>   Installing MIPS System Image, Android API 16, revision 1
>     Installed MIPS System Image, Android API 16, revision 199%)
>   Skipping 'ARM EABI v7a System Image, Android API 15, revision 3'; it depends on 'SDK Platform Android 4.0.3, API 15, revision 5' which was not installed.
>   Skipping 'Intel x86 Atom System Image, Android API 15, revision 2'; it depends on 'SDK Platform Android 4.0.3, API 15, revision 5' which was not installed.
>   Skipping 'MIPS System Image, Android API 15, revision 1'; it depends on 'SDK Platform Android 4.0.3, API 15, revision 5' which was not installed.
>   Skipping 'ARM EABI v7a System Image, Android API 14, revision 2'; it depends on 'SDK Platform Android 4.0, API 14, revision 4' which was not installed.
>   Skipping 'Intel x86 Atom System Image, Android API 10, revision 3'; it depends on 'SDK Platform Android 2.3.3, API 10, revision 2' which was not installed.
>     Stopping ADB server succeeded.
>     Starting ADB server succeeded.
>   Done. 6 packages installed.
> Valid ABIs: default/armeabi-v7a, default/mips, default/x86
> Error: This platform has more than one ABI. Please specify one using --abi.
> The command '/bin/sh -c expect /build/accept-licenses "android update sdk --no-ui --all --filter platform-tool,system-image,android-16" "android-sdk-license-5be876d5" &&     echo "\n"| android create avd -n droidbox -t 1 -d 2' returned a non-zero code: 1

I'm using Linux (4.5.1)
I opted to build it myself because i want to get the logcat file together with the output of droidbox when examining a apk (and this was not possible otherwise).

**Comment by aikinci** [comment]
Note that this has been fixed in the upstream docker image at https://github.com/aikinci/droidbox 
It is the fact that each new sdk version has a different license identifier.

**Comment by Nooby4Ever** [comment]
Alright thanks, when i try to build the upstream docker image i got the following error message:

> ...
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists...
> Building dependency tree...
> Package openjdk-7-jre-headless is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'openjdk-7-jre-headless' has no installation candidate
> ... returned a non-zero code: 100

But since this is an upstream issue i will close this one.
